name: ci-cd pipeline

on: 
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with: 
        node-version: '14'
    
    - name: Install dependencies
      run: npm install

    - name: Deploy to EC2
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        EC2_USER: ubuntu
        EC2_HOST: ec2-13-200-251-118.ap-south-1.compute.amazonaws.com
        EC2_PATH: /home/ubuntu/ci-cd
      run: |
        echo "$EC2_SSH_KEY" > ec2_key.pem
        chmod 600 ec2_key.pem
        ssh -i ec2_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << EOF
          # Install Node.js and npm if not already installed
          if ! command -v node &> /dev/null
          then
            curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs
          fi
          # Create the directory if it doesn't exist
          if [ ! -z "$EC2_PATH" ]; then
            mkdir -p $EC2_PATH
          fi
          exit
        EOF
        # Copy files to EC2
        rsync -avz --exclude '.git' --exclude 'node_modules' -e "ssh -i ec2_key.pem -o StrictHostKeyChecking=no" . $EC2_USER@$EC2_HOST:$EC2_PATH
        # Run commands on EC2
        ssh -i ec2_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << EOF
          cd $EC2_PATH
          npm install
          pm2 restart all || pm2 start index.js
        EOF
